test = ['S+1', 'Sr', 'I+2', 'N-1', 'Cs', 'Pd+1', 'Pd-4', 'Al+2', 'H', 'In+3', 'Ti+3', 'C+4', 'Li+1', 'Hg', 'Zn+2', 'Cr', 'Al+1', 'F', 'Si-1', 'Cu', 'C-1', 'Ag', 'Yb+3', 'Al+3', 'Ag-1', 'Zn+1', 'Ca', 'Ga', 'Ce+4', 'Na+1', 'Ba+2', 'Pb+4', 'Pt', 'Fe+3', 'K', 'Zr+1', 'Cu+1', 'P', 'Eu+3', 'Zr+2', 'Mg+2', 'B+3', 'I+1', 'Cs+1', 'Ag+2', 'H-1', 'B+1', 'Rh+1', 'Se-1', 'Rh', 'Pd-2', 'B+2', 'Zr+4', 'Tl+3', 'I', 'Cr+3', 'P-1', 'O', 'Nd+3', 'Cl+3', 'N', 'Ir', 'Br', 'S', 'Se', 'Os', 'Sn+1', 'Mg+1', 'Na', 'Hg+2', 'Ce', 'Ca+2', 'Sn', 'Cu+2', 'Zn', 'Ni+2', 'Re', 'Cl+2', 'Pb+3', 'Pd', 'C', 'Ru', 'Al-1', 'Sn+2', 'Ti+2', 'Sb', 'F-1', 'As', 'Pb', 'S-1', 'P+5', 'Pd-1', 'I-1', 'Mn', 'Ni', 'Ti', 'P+1', 'Ag+1', 'O-1', 'Rh+2', 'Cl', 'W', 'I+3', 'Cl-1', 'C+1', 'Co', 'Li', 'Au', 'Sr+2', 'B-1', 'Br+2', 'Al', 'Co+2', 'O+1', 'Fe+2', 'Ge', 'Ce+3', 'K+1', 'Ti+4', 'Br-1', 'B', 'Mo', 'Si', 'N+1', 'Fe', 'H+1', 'Ru+2', 'Sc+3', 'In', 'Rh+3', 'Mg', 'Mn+2', 'Pd+2', 'Cl+1', 'Mn+3', 'Zr']


train = ['S+1', 'Sr', 'I+2', 'N-1', 'Cs', 'Cd+1', 'Pd+1', 'Sm+2', 'Pd-4', 'Hf', 'Al+2', 'H', 'In+3', 'Ti+3', 'C+4', 'Li+1', 'Hg', 'Fe-3', 'Zn+2', 'Pt-1', 'Cr', 'Al+1', 'F', 'Zr+3', 'Si-1', 'Cu', 'C-1', 'Ag', 'Yb+3', 'As+1', 'Pr+3', 'Al+3', 'Ag-1', 'Ta+2', 'Sb+5', 'N+3', 'Zn+1', 'Ca', 'Ga', 'Fe-4', 'Nd+1', 'Cr+6', 'Ti+1', 'Nd', 'La+3', 'Ce+4', 'Ba+2', 'Na+1', 'Y+3', 'Pb+4', 'Pt', 'Pb+2', 'Fe+3', 'K', 'Zr+1', 'Tl+2', 'Cu+1', 'In+1', 'V', 'He', 'Pt+2', 'Be+2', 'P', 'Eu+3', 'Yb', 'Zr+2', 'Mg+2', 'B+3', 'I+1', 'Cs+1', 'Ag+2', 'Ni+1', 'V+4', 'H-1', 'Sm+3', 'Rh+1', 'B+1', 'Hg+1', 'Hf+4', 'Se-1', 'Tl+1', 'Rh', 'Sm', 'Xe', 'La', 'Pd-2', 'Cd+2', 'B+2', 'Zr+4', 'Tl+3', 'Ru-2', 'V+3', 'I', 'Cr+3', 'P-1', 'O', 'Ga+2', 'Co+1', 'Nd+3', 'Cl+3', 'N', 'Ta', 'Ir', 'Br', 'S', 'Se', 'Os', 'Sn+1', 'Mg+1', 'Tl', 'Na', 'Hg+2', 'Cu+3', 'Ce', 'Ca+2', 'Sn', 'Co+3', 'Cr+2', 'Cu+2', 'Zn', 'Re', 'Ni+2', 'Cl+2', 'Pb+3', 'Pd', 'C', 'Ru', 'Al-1', 'Sn+2', 'Ti+2', 'Cd', 'Sb', 'Bi+3', 'F-1', 'As', 'Pb', 'S-1', 'Ga+3', 'P+5', 'Pd-1', 'Ti+5', 'Pt+3', 'I-1', 'Mn', 'Ni', 'Ti', 'P+1', 'Rb+1', 'Ag+1', 'Au-1', 'O-1', 'Rh+2', 'Dy+3', 'Sn+4', 'Cl', 'W', 'Bi', 'I+3', 'Cl-1', 'C+1', 'Co', 'Li', 'Au', 'Ce+2', 'Sr+2', 'P+3', 'B-1', 'Br+2', 'Al', 'Te', 'Ni+3', 'Co+2', 'O+1', 'Ta+5', 'Fe+2', 'Br+1', 'Ge', 'Ce+3', 'K+1', 'Ti+4', 'Br-1', 'Ga+1', 'Sc', 'B', 'In', 'Si', 'N+1', 'Fe', 'H+1', 'Ar', 'Sc+3', 'Rh+3', 'Mo', 'Ba', 'Ru+2', 'Mg', 'Mn+2', 'Pd+2', 'Cl+1', 'Mn+3', 'Zr']


val = ['S+1', 'I+2', 'N-1', 'Pd-4', 'Al+2', 'H', 'In+3', 'Ti+3', 'C+4', 'Li+1', 'Hg', 'Fe-3', 'Zn+2', 'Cr', 'Al+1', 'F', 'Si-1', 'Cu', 'C-1', 'Ag', 'Yb+3', 'Al+3', 'Ag-1', 'Zn+1', 'Ca', 'Nd+1', 'Nd', 'Ce+4', 'Na+1', 'Ba+2', 'Pb+4', 'Pt', 'Pb+2', 'Fe+3', 'K', 'Cu+1', 'P', 'Mg+2', 'B+3', 'I+1', 'Cs+1', 'Ag+2', 'H-1', 'Sm+3', 'B+1', 'Rh+1', 'Hg+1', 'Rh', 'B+2', 'Zr+4', 'Tl+3', 'I', 'P-1', 'O', 'Cl+3', 'N', 'Ta', 'Br', 'S', 'Se', 'Os', 'Sn+1', 'Mg+1', 'Na', 'Hg+2', 'Ce', 'Ca+2', 'Sn', 'Cu+2', 'Zn', 'Ni+2', 'Re', 'Cl+2', 'Pd', 'C', 'Sn+2', 'Ru', 'Al-1', 'Sb', 'F-1', 'As', 'Pb', 'S-1', 'P+5', 'Si+1', 'I-1', 'Mn', 'Ni', 'Ti', 'P+1', 'Ag+1', 'O-1', 'Rh+2', 'Cl', 'W', 'Bi', 'I+3', 'Cl-1', 'C+1', 'Co', 'Li', 'Sn+3', 'Au', 'B-1', 'Br+2', 'Al', 'Co+2', 'O+1', 'Ta+5', 'Fe+2', 'Ge', 'Ce+3', 'K+1', 'Ti+4', 'Br-1', 'Sc', 'B', 'In', 'Si', 'N+1', 'Fe', 'H+1', 'Ar', 'Rh+3', 'Sc+3', 'Ru+2', 'Mo', 'Mg', 'Mn+2', 'Pd+2', 'Cl+1', 'Zr']


test_not_in_train = [a for a in test if a not in train]

val_not_in_train  = [a for a in val if a not in train]

print(f'test_not_in_train {test_not_in_train}\n')
print(f'val_not_in_train {val_not_in_train}\n')
