name: 'uspto-full-ring-opening-charged'
dataset_nb: 'charged-40-block'
datadir: 'data/uspto-full-ring-opening'
datadist_dir: 'data/uspto-full-ring-opening'
process_only: none
pin_memory: True
num_workers: 0
num_processes: 8
shuffle: True
with_formal_charge: True
with_formal_charge_in_atom_symbols: True
use_charges_as_features: False # deprecated
nb_rct_dummy_nodes: 40 # change this
batchsize_bins: {'train': [16, 16], 'test': [16], 'val': [16]}
size_bins: {'train': [200, 400], 'test': [250],'val': [250]}
dataset_size:
  train: 17418
  test: 2196
  val: 2202
pre_align_graphs: True
permute_mols: False
canonicalize_molecule: False 
use_stereochemistry: False
recalculate_atom_maps: False
drop_atom_maps_rate: 0.0
add_product_identifier: False
atom_types: ['none', 'Se', 'P-1', 'Cu', 'Al-1', 'N+1', 'S-1', 'Ru', 'Pt', 'O', 'Br-1', 'B', 'Al', 'C', 'Na', 
            'Al+2', 'W', 'S', 'N', 'H-1', 'Mn', 'Br+2', 'Mg', 'N-1', 'Sn', 'O+1', 'Cl', 'Cl-1', 'F-1', 
            'S+1', 'P+1', 'H', 'Cl+3', 'Al+1', 'K', 'S-2', 'Mg+1', 'I-1', 'Si-1', 'Li', 'Zn+1', 'P', 'O-1', 'F', 'Cr', 'C-1', 
            'B-1', 'O-2', 'Cl+2', 'C+1', 'I+3', 'I', 'Si', 'Zn', 'Tl+2', 'Br', 'U', 'Au', 'SuNo']
atom_charges: [0, 1, 2, 3, -2, -1]
bond_types: ['none', 'SINGLE', 'DOUBLE', 'TRIPLE', 'mol', 'within', 'across']
atom_chiral_tags: ['none', 'ccw', 'cw']
bond_dirs: ['none', 'ENDUPRIGHT', 'ENDDOWNRIGHT']
allowed_bonds:
  "Se": [2, 4, 6]
  "P-1": [2, 4, 6]
  "Cu": [-1]
  "Al-1": [2, 5]
  "N+1": [4]
  "S-1": [1, 3, 5]
  "Ru": [-1]
  "Pt": [-1]
  "O": [2]
  "Br-1": [0]
  "B": [3]
  "Al": [3, 6]
  "C": [4]
  "Na": [1, -1]
  "Al+2": [5, 8]
  "W": [-1]
  "S": [2, 4, 6]
  "N": [3]
  "H-1": [0]
  "Mn": [-1]
  "Br+2": [3]
  "Mg": [2, -1]
  "N-1": [2]
  "Sn": [2, 4]
  "O+1": [3]
  "Cl": [1]
  "Cl-1": [0]
  "F-1": [0]
  "S+1": [3, 5, 7]
  "P+1": [4, 6, 8]
  "H": [1]
  "Cl+3": [4]
  "Al+1": [4, 7]
  "K": [1, -1]
  "S-2": [0, 2, 4]
  "Mg+1": [3, 0]
  "I-1": [0, 2, 4]
  "Si-1": [3, 5]
  "Li": [1, -1]
  "Zn+1": [0]
  "P": [3, 5, 7]
  "O-1": [1]
  "F": [1]
  "Cr": [-1]
  "C-1": [3]
  "B-1": [2]
  "O-2": [0]
  "Cl+2": [3]
  "C+1": [5]
  "I+3": [4, 6, 8]
  "I": [1, 3, 5]
  "Si": [4, 6]
  "Zn": [-1]
  "Tl+2": [5]
  "Br": [1]
  "U": [6]
  "Au": [0]
zero_bond_order: False
different_valencies: False 
add_supernode_edges: False
add_supernodes: False
remove_h: False # deprecated
with_explicit_h: False # deprecated

