name: 'uspto-full'
dataset_nb: 'dummy20-stereo-charges-in-atom-types-reassign-am'
datadir: 'data/uspto-full'
datadist_dir: 'data/uspto-full'
pin_memory: False
remove_h: False
shuffle: True
with_explicit_h: False
with_formal_charge: True
add_supernode_edges: False
add_supernodes: True
nb_rct_dummy_nodes: 20 # used to be 40 but cut down on it
num_workers: 0
num_processes: 8
permute_mols: False
pre_align_graphs: True
different_valencies: True # needs to be this for uspto-full 
zero_bond_order: False
recalculate_atom_maps: True
process_only: none # which dataset to process separately in the start of the Dataset loading (work-around a bug with the dataset processing)
batchsize_bins: {'train': [16, 16, 16, 8, 4, 1, 1], 'test': [16], 'val': [16]}
size_bins: {'train': [64, 83, 102, 140, 200, 300, 400], 'test': [250],'val': [250]}
canonicalize_molecule: False
atom_types: ['none', 'Sn', 'Cd+2', 'Cr+2', 'Ba', 'Mg', 'Hg+1', 'I+1', 'Al+3', 'O-1', 'N-1', 'Al-1',
              'Nd', 'Br+1', 'Co', 'Ta+5', 'I+2', 'Zr', 'Ti', 'S-2', 'Rh', 'Hg', 'Ga+3', 'Si', 'Tb+3', 
              'V+2', 'Cl+1', 'Ta', 'P', 'Hg+2', 'Au-1', 'P-1', 'La+3', 'Cu', 'Ca+2', 'Ag+3', 'Eu+3', 'In+1',
              'S-1', 'C+4', 'Sn+2', 'Pb+3', 'Ba+2', 'Zr+4', 'Mn', 'Ga+2', 'Xe', 'Mg+2', 'Ti+3', 'Ag', 'P+1', 
              'Fe+2', 'Si+1', 'N+1', 'F-1', 'Mo', 'Sb-1', 'B', 'S', 'Pd', 'Cl', 'Sm+3', 'Nd+3', 'P+3', 'Na',
              'La', 'Ce', 'Re', 'Mn+2', 'V', 'Pt-1', 'Cs+1', 'Pt', 'Zn+1', 'Tl', 'Cr+3', 'Dy+3', 'Al+1', 'Li+1',
              'Na+1', 'B+2', 'Ti+4', 'Fe+3', 'Cu-2', 'B+1', 'In', 'O', 'As-1', 'Li', 'I-1', 'Se-1', 'Se', 'Al', 
              'Co+2', 'Ag+1', 'Te', 'Cu+1', 'V+5', 'Pb+4', 'Co+3', 'Si-1', 'Ta+2', 'Bi+3', 'Ag+2', 'Au', 'As+1', 
              'N', 'C-1', 'Sm', 'K', 'Zn+2', 'Pd+2', 'Pt-2', 'Cr', 'Gd+3', 'Ni+2', 'Se+1', 'Ca', 'Cl+2', 'Zr+3', 
              'B-1', 'Ag-1', 'Sr', 'Ga', 'Tl+2', 'Cd', 'Sr+2', 'Bi', 'Cl+3', 'Cl-1', 'Br+2', 'Zr+2', 'O-2', 'Cu-1',
              'Fe-4', 'Sn+1', 'Fe', 'Al+2', 'Zn', 'C', 'Y', 'C+1', 'Ga+1', 'H-1', 'Mo+4', 'Cu+2', 'I', 'As', 'W', 
              'Pb', 'Cr-1', 'F', 'Ru', 'Pt+2', 'H', 'K+1', 'Br-1', 'Rh+2', 'Br', 'Gd', 'Mg+1', 'Cr+6', 'P+2', 'Ni', 'Ge', 
              'S+1', 'Ti+2', 'Se-2', 'Sb', 'O+1', 'I+3', 'U', 'SuNo']
bond_types: ['none', 'SINGLE', 'DOUBLE', 'TRIPLE', 'mol', 'within', 'across']
atom_charges: [0, 1, 2, 3, 4, 5, 6, -2, -4, -1]
atom_chiral_tags: ['none', 'ccw', 'cw']
bond_dirs: ['none', 'ENDUPRIGHT', 'ENDDOWNRIGHT']
with_formal_charge_in_atom_symbols: True
use_stereochemistry: False
use_charges_as_features: False
drop_atom_maps_rate: 0.0
allowed_bonds:
  "Sn": [2]
  "Cd+2": [1]
  "Cr+2": [1]
  "Ba": [2]
  "Mg": [2]
  "Hg+1": [0]
  "I+1": [2]
  "Al+3": [6]
  "O-1": [1]
  "N-1": [2]
  "Al-1": [2]
  "Nd": [-1]
  "Br+1": [2]
  "Co": [-1]
  "Ta+5": [4]
  "I+2": [3]
  "Zr": [-1]
  "Ti": [-1]
  "S-2": [0]
  "Rh": [-1]
  "Hg": [-1]
  "Ga+3": [6]
  "Si": [4]
  "Tb+3": [2]
  "V+2": [1]
  "Cl+1": [2]
  "Ta": [-1]
  "P": [3]
  "Hg+2": [1]
  "Au-1": [-2]
  "P-1": [2]
  "La+3": [2]
  "Cu": [-1]
  "Ca+2": [4]
  "Ag+3": [2]
  "Eu+3": [2]
  "In+1": [4]
  "S-1": [1]
  "C+4": [8]
  "Sn+2": [4]
  "Pb+3": [5]
  "Ba+2": [4]
  "Zr+4": [3]
  "Mn": [-1]
  "Ga+2": [5]
  "Xe": [0]
  "Mg+2": [4]
  "Ti+3": [2]
  "Ag": [-1]
  "P+1": [4]
  "Fe+2": [1]
  "Si+1": [5]
  "N+1": [4]
  "F-1": [0]
  "Mo": [-1]
  "Sb-1": [2]
  "B": [3]
  "S": [2]
  "Pd": [-1]
  "Cl": [1]
  "Sm+3": [2]
  "Nd+3": [2]
  "P+3": [6]
  "Na": [1]
  "La": [-1]
  "Ce": [-1]
  "Re": [-1]
  "Mn+2": [1]
  "V": [-1]
  "Pt-1": [-2]
  "Cs+1": [2]
  "Pt": [-1]
  "Zn+1": [0]
  "Tl": [3]
  "Cr+3": [2]
  "Dy+3": [2]
  "Al+1": [4]
  "Li+1": [2]
  "Na+1": [2]
  "B+2": [5]
  "Ti+4": [3]
  "Fe+3": [2]
  "Cu-2": [-3]
  "B+1": [4]
  "In": [3]
  "O": [2]
  "As-1": [2]
  "Li": [1]
  "I-1": [0]
  "Se-1": [1]
  "Se": [2]
  "Al": [3]
  "Co+2": [1]
  "Ag+1": [0]
  "Te": [2]
  "Cu+1": [0]
  "V+5": [4]
  "Pb+4": [6]
  "Co+3": [2]
  "Si-1": [3]
  "Ta+2": [1]
  "Bi+3": [6]
  "Ag+2": [1]
  "Au": [-1]
  "As+1": [4]
  "N": [3]
  "C-1": [3]
  "Sm": [-1]
  "K": [1]
  "Zn+2": [1]
  "Pd+2": [1]
  "Pt-2": [-3]
  "Cr": [-1]
  "Gd+3": [2]
  "Ni+2": [1]
  "Se+1": [3]
  "Ca": [2]
  "Cl+2": [3]
  "Zr+3": [2]
  "B-1": [2]
  "Ag-1": [-2]
  "Sr": [2]
  "Ga": [3]
  "Tl+2": [5]
  "Cd": [-1]
  "Sr+2": [4]
  "Bi": [3]
  "Cl+3": [4]
  "Cl-1": [0]
  "Br+2": [3]
  "Zr+2": [1]
  "O-2": [0]
  "Cu-1": [-2]
  "Fe-4": [-5]
  "Sn+1": [3]
  "Fe": [-1]
  "Al+2": [5]
  "Zn": [-1]
  "C": [4]
  "Y": [-1]
  "C+1": [5]
  "Ga+1": [4]
  "H-1": [0]
  "Mo+4": [3]
  "Cu+2": [1]
  "I": [1]
  "As": [3]
  "W": [-1]
  "Pb": [2]
  "Cr-1": [-2]
  "F": [1]
  "Ru": [-1]
  "Pt+2": [1]
  "H": [1]
  "K+1": [2]
  "Br-1": [0]
  "Rh+2": [1]
  "Br": [1]
  "Gd": [-1]
  "Mg+1": [3]
  "Cr+6": [5]
  "P+2": [5]
  "Ni": [-1]
  "Ge": [4]
  "S+1": [3]
  "Ti+2": [1]
  "Se-2": [0]
  "Sb": [3]
  "O+1": [3]
  "I+3": [4]
  "U": [-1]
dataset_size:
  train: 810496
  test: 101311
  val: 101311