name: 'uspto-full-uncharged-atom-types'
dataset_nb: 'dummy15-stereo-charges-separate'
datadir: 'data/uspto-full'
datadist_dir: 'data/uspto-full'
pin_memory: False
remove_h: False
shuffle: True
with_explicit_h: False
with_formal_charge: False
add_supernode_edges: True
nb_rct_dummy_nodes: 15
num_workers: 0
permute_mols: False
num_processes: 8
zero_bond_order: False
batchsize_bins: {'train': [16, 16], 'test': [16], 'val': [16]}
size_bins: {'train': [200, 400], 'test': [250],'val': [250]}
# batchsize_bins: {'train': [16, 16, 16, 16, 8, 2, 1], 'test': [16], 'val': [16]}
# size_bins: {'train': [64, 83, 102, 140, 200, 300, 400], 'test': [250],'val': [250]}
canonicalize_molecule: False # This slows down the preprocessing a lot, and is not necessary since we deal with atom mapping in other ways
# atom_types: ['none', 'C', 'Ce', 'F', 'Cr', 'P', 'Pt', 'Co', 'As', 'Dy', 'Bi', 'Pr', 'He', 'Rb', 'Ir', 'Zr', 'Ca', 'Yb', 'V', 'Sn', 'Y', 'Ge', 'Pd', 'Cd', 'H', 'Nd', 'Hg', 'Pb', 'Mn',
#              'La', 'In', 'Te', 'Tl', 'Rh', 'Hf', 'Au', 'Si', 'Sm', 'Sr', 'Ni', 'Re', 'S', 'Mo', 'Li', 'Al', 'Na', 'W', 'Fe', 'Ta', 'Eu', 'Sb', 'Br', 'Ga', 'B', 'Ag', 'Ru', 'Cl', 'I', 'Os', 'Ar', 
#              'Mg', 'Ti', 'K', 'Xe', 'Be', 'O', 'Cs', 'N', 'Cu', 'Se', 'Sc', 'Ba', 'Zn','U', 'Tb', 'Gd', 'SuNo']
atom_types: ['none', 'C', 'Cd', 'W', 'Al', 'Nd', 'S', 'Ce', 'O', 'Gd', 'Co', 'Cr', 'Sm', 'Au', 'Zn', 'Br', 'As', 'Mn', 'Y', 'In', 'Zr', 'Ga', 'B', 'F', 'Ru', 'Se', 
             'K', 'Cl', 'Ti', 'H', 'V', 'P', 'Re', 'Sr', 'Eu', 'Sb', 'Pb', 'Tb', 'Sn', 'Dy', 'Mo', 'Ag', 'Tl', 'I', 'Ni', 'Cs', 'La', 'Bi', 'Xe', 'Mg', 'N', 'Pt', 
             'Hg', 'Rh', 'Ba', 'Ta', 'Si', 'Cu', 'Li', 'Pd', 'Fe', 'Na', 'Te', 'Ca', 'Ge', 'U', 'SuNo']
# bond_types: ['none', 'SINGLE', 'DOUBLE', 'TRIPLE', 'mol', 'within', 'across']
bond_types: ['none', 'SINGLE', 'DOUBLE', 'TRIPLE']
atom_charges: [0, 1, 2, 3, 4, 5, 6, -2, -4, -1]
atom_chiral_tags: ['none', 'ccw', 'cw']
bond_dirs: ['none', 'ENDUPRIGHT', 'ENDDOWNRIGHT']
with_formal_charge_in_atom_symbols: False
use_stereochemistry: True
use_charges_as_features: True
drop_atom_maps_rate: 0.0
allowed_bonds:
  "C": [4]
  "Cd": [-1]
  "W": [-1]
  "Al": [3]
  "Nd": [-1]
  "S": [2]
  "Ce": [-1]
  "O": [2]
  "Gd": [-1]
  "Co": [-1]
  "Cr": [-1]
  "Sm": [-1]
  "Au": [-1]
  "Zn": [-1]
  "Br": [1]
  "As": [3]
  "Mn": [-1]
  "Y": [-1]
  "In": [3]
  "Zr": [-1]
  "Ga": [3]
  "B": [3]
  "F": [1]
  "Ru": [-1]
  "Se": [2]
  "K": [1]
  "Cl": [1]
  "Ti": [-1]
  "H": [1]
  "V": [-1]
  "P": [3]
  "Re": [-1]
  "Sr": [2]
  "Eu": [-1]
  "Sb": [3]
  "Pb": [2]
  "Tb": [-1]
  "Sn": [2]
  "Dy": [-1]
  "Mo": [-1]
  "Ag": [-1]
  "Tl": [3]
  "I": [1]
  "Ni": [-1]
  "Cs": [1]
  "La": [-1]
  "Bi": [3]
  "Xe": [0]
  "Mg": [2]
  "N": [3]
  "Pt": [-1]
  "Hg": [-1]
  "Rh": [-1]
  "Ba": [2]
  "Ta": [-1]
  "Si": [4]
  "Cu": [-1]
  "Li": [1]
  "Pd": [-1]
  "Fe": [-1]
  "Na": [1]
  "Te": [2]
  "Ca": [2]
  "Ge": [4]
  "U": [-1]
dataset_size:
  train: 810496
  test: 101311
  val: 101311