training:
    epochs: 100
    val_interval: 10
    print_every: 10
    save_every: 10
    batch_size: 12
    checkpoint_dir: "checkpoints"
    log_to_wandb: true
    log_every_steps: 10
    learning_rate: 1e-4
    step_size: 10
    gamma: 0.9
    max_nodes_for_training: 100
    use_mixed_precision: false
    use_bfloat16: false
    use_ema: false
    ema_decay: 0.999
    use_data_parallel: false
    use_all_gpus: false
    use_all_cpus: false
    use_all_gpus_for_evaluation: false
    use_all_cpus_for_evaluation: false
    use_all_gpus_for_training: false
    use_all_cpus_for_training: false

dataset:
    num_dummy_nodes: 10
    data_dir: uspto_50k
    atom_types_path: atom_types.txt
    atom_charges_path: atom_charges.txt
    atom_chiral_tags_path: atom_chiral_tags.txt
    atom_types_charged_path: atom_types_charged.txt
    bond_types_path: bond_types.txt
    bond_dirs_path: bond_dirs.txt
    with_formal_charge_in_atom_symbols: false
    canonicalize_molecule: false
    dummy_node_type: 'U'
    use_stereochemistry: true
    use_charges_as_features: false
    atom_charges: []

neuralnet:
    extra_features: false
    increase_y_dim_for_multigpu: false
    pos_emb_permutations: 10
    architecture: with_y_atommap_number_pos_enc_stereo
    hidden_dims:
        dx: 16
        de: 16
        dy: 16
        n_head: 4
        dim_ffX: 2
        dim_ffE: 2
    hidden_mlp_dims:
        X: 16
        E: 16
        y: 16
        atom_chiral: 16
        bond_dirs: 16
        dx: 16
        de: 16
        dy: 16
    n_layers: 2
    improved: false
    dropout: 0.1
    p_to_r_skip_connection: false
    p_to_r_init: 10.
    alignment_type: old
    input_alignment: false
    use_ema: false
    ema_decay: 0.999

diffusion:
    diffusion_steps: 1000
    beta_1: 0.0001
    beta_T: 0.02
    schedule: linear
    loss_type: mse
    weight_decay: 0.0
    clip_grad_norm: 1.0
    log_every_steps: 100
    node_states_to_mask: []
    edge_states_to_mask: []
    transition: uniform
    diffusion_steps_eval: 10
    diffusion_noise_schedule: cosine
    diffuse_edges: true