"dataset": {
    "desc": null,
    "value": {
      "name": "uspto-50k",
      "datadir": "data/uspto-50k",
      "shuffle": true,
      "remove_h": false,
      "size_bins": {
        "val": [
          250
        ],
        "test": [
          250
        ],
        "train": [
          64,
          83,
          102,
          140
        ]
      },
      "dataset_nb": "block-15",
      "pin_memory": false,
      "num_workers": 0,
      "datadist_dir": "data/uspto-50k",
      "batchsize_bins": {
        "val": [
          64
        ],
        "test": [
          64
        ],
        "train": [
          120,
          56,
          16,
          8
        ]
      },
      "with_explicit_h": false,
      "nb_rct_dummy_nodes": 15,
      "with_formal_charge": true,
      "add_supernode_edges": true,
      "canonicalize_molecule": true
    }
  }